abstract: Apache2 module to authentificate trough a CAS server
author: Yves Agostini
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Apache2-AuthCASSimple
no_index: 
  directory: 
    - inc
    - t
requires: 
  Apache2::Connection: 0
  Apache2::Const: 0
  Apache2::Log: 0
  Apache2::RequestRec: 0
  Apache2::RequestUtil: 0
  Apache::Session::Wrapper: 0
  Authen::CAS::Client: 0
tests: t/*.t
version: 0.0.2
