abstract: Apache2 module to authentificate trough a CAS server
author: Yves Agostini
build_requires: 
  Pod::Coverage: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Apache2-AuthCASSimple
no_index: 
  directory: 
    - inc
    - t
requires: 
  Apache::Session::Wrapper: 0
  Authen::CAS::Client: 0
  mod_perl2: 2
  perl: 5.6.0
tests: t/*.t
version: 0.0.3
