abstract: Apache2 module to authentificate trough a CAS server
author: Yves Agostini
build_requires: 
  Apache2::Connection: 0
  Apache2::Log: 0
  Apache::Session::Wrapper: 0
  Authen::CAS::Client: 0
  Pod::Coverage: 0
  Test::More: 0
  mod_perl2: 1.99
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Apache2-AuthCASSimple
no_index: 
  directory: 
    - examples
    - inc
    - t
requires: 
  Apache2::Connection: 0
  Apache2::Log: 0
  Apache::Session::Wrapper: 0
  Authen::CAS::Client: 0
  mod_perl: 1.99
  perl: 5.8.0
tests: t/*.t
version: 0.05
